layouts/partials/candidate-list.html, static/scss/style.scss
=> Layouts: Add a filter to candidate list

content/state-house/_index.md, content/state-senate/_index.md, data/stateDistricts.json, layouts/district-list/list.html, layouts/partials/ad-leaderboard.html, layouts/partials/ad-rightrail.html, layouts/partials/candidate-list.html, static/scss/ads.scss, static/scss/app.scss, static/scss/district-list.scss, static/scss/style.scss
=> District list: Add descriptions for state districts

layouts/_default/single.html, layouts/index.html, layouts/partials/coverage.html, static/scripts/javascript.js
=> RSS Coverage: Break out coverage as partial and add to homepage

csv/02-districts.csv, csv/03-local.csv, layouts/district-list/list.html, layouts/partials/candidate-list.html
It turns out some races are by district and Harford is a special snowflake. This deals with that.
=> Add local sub-districts for County Council and Board of Education

package.json
This restores content/ to its checked in state.
=> Yarn: Add clean:content command

cmd/csv-splitter/csv-splitter.go
This will help with the Sun endorsement column.
=> CSV Splitter: Translate Yes/No/True/False to true/false in JSON

layouts/_default/single.html, static/scss/style.scss
- This fixes an issue where there are multiple IDs with the same name
- It adds some missing alt tags
- Tweaks the image to be more prominent on mobile
=> Front-end: Fix validation issues, tweak mobile look

layouts/_default/single.html, static/scss/app.scss, static/scss/candidate.scss
=> Candidate page: Add prev/next candidate links

README.md, cmd/robocopy/controller.go, cmd/robocopy/model_metadata.go, cmd/robocopy/robocopy.go, layouts-robocopy/contest.html, static/scss/style.scss
This also adds the changes from the cp/primary-design branch.
=> Robocopy: Add reporting, change sub-districts

cmd/robocopy/controller.go, cmd/robocopy/controller_test.go, cmd/robocopy/json.go, cmd/robocopy/model_metadata.go, cmd/robocopy/robocopy.go, cmd/robocopy/uploader.go, data/results.json, layouts-robocopy/contest.html, layouts/results-page/single.html, static/scripts/javascript.js
=> Robocopy: Fix some missing info in results, add other lookup methods

layouts/partials/ad-autorefresh.html, layouts/partials/ad-scripts.html, layouts/results-page/single.html, static/scripts/javascript.js
Since the page is going to be open, theoretically for a long time, this adds an autorefreshing ad to the page.
=> JS: Add an autorefreshing ad type

static/scripts/javascript.js
Apparently, RSS2JSON is based in Holland.
=> JS: Use Yahoo for feed fetching because GDPR

content/governor/alec-ross.md, content/governor/ben-jealous.md, content/governor/jim-shea.md, content/governor/kevin-kamenetz.md, content/governor/krish-omara-vignarajah.md, content/governor/rich-madaleno.md, content/governor/rushern-l-baker-iii.md, content/governor/valerie-ervin.md, layouts/_default/single.html, static/scss/style.scss
Hey look, it's a diff that you can read!!
You can take over this branch with the HTML/CSS changes and we can merge once that's ready.
=> Content: Add interview/profile metadata for governor candidates

cmd/robocopy/json.go, data/KeyContests2018Primary.json, data/results.json, layouts/results-page/single.html
- Fix label on senate races
- Order districts by ID
=> Data: Tweak results data

Gopkg.lock, cmd/robocopy/robocopy.go, layouts-robocopy/contest.html, static/scss/results.scss
=> Robocopy: Add some template functions

static/scss/style.scss
There was a bug in the style parser.
=> CSS: A couple other styles got missed

cmd/robocopy/robocopy.go, cmd/robocopy/server.go, cmd/robocopy/uploader.go, layouts-robocopy/story.html
This one will be at http://localhost:9191/results/bs-2018-elections-primary-story when you run -dev-server.
=> Robocopy: Add a P2P story too for the mobile app

cmd/robocopy/controller.go
Use like `{{ range $gov.TopN 2 }}` ... . If votes are 0, it returns nothing, so check with `{{ if gt (len whatever) 0 }}`.
=> Robocopy: Add .TopN template function

layouts-robocopy/contest.html
This looks a little nicer than a zero.
=> Contest result: Use dash instead of zero for no data

content/dates.md
=> Content: Strikethrough old dates

.dockerignore, .gitignore, config.toml, layouts/_default/baseof.html, layouts/_default/single.html
I'm just going to merge once the tests pass because the site is missing candidate photos now.
=> Fix for broken images in upgrade version

.dockerignore, .gitignore, config.toml, layouts/_default/baseof.html, layouts/results-page/single.html
This reverts commit 183fd7c585b5c4617b5c474bc875f4d64d61bc6d.
=> Layouts: Fix for broken results page

content/howard-county/county-council/district-1/raj-kathuria.md, content/howard-county/county-council/district-2/john-liao.md, content/howard-county/county-council/district-2/opel-jones.md, content/howard-county/county-council/district-3/christiana-rigby.md, content/howard-county/county-council/district-4/deb-jung.md, content/howard-county/county-council/district-4/lisa-kim.md, content/howard-county/county-council/district-5/china-williams.md, content/howard-county/county-council/district-5/david-yungmann.md, content/primary/howard-county/county-council/district-1/jon-weinstein.md
These weren't moved from endorsement to primary-endorsement before, so they were still showing up.
=> Content: Fix Howard endorsements

cmd/csv-splitter/csv-splitter.go, content/harford-county/county-council/district-a/andre-v-johnson.md, content/harford-county/county-council/district-a/donna-blasdell.md, content/harford-county/county-council/district-b/joe-woods.md, content/harford-county/county-council/district-b/suzanne-oshinsky.md, content/harford-county/county-council/district-c/karen-kukurin.md, content/harford-county/county-council/district-c/tony-g-giangiordano.md, content/harford-county/county-council/district-d/chad-r-shrodes.md, content/harford-county/county-council/district-d/jean-m-salvatore.md, content/harford-county/county-council/district-e/bridgette-johnson.md, content/harford-county/county-council/district-e/robert-s-wagner.md, content/harford-county/county-council/district-f/curtis-l-beulah.md, content/harford-county/county-council/district-f/winifred-wini-roche.md, content/primary/harford-county/county-council/district-a/dion-f-guthrie.md, content/primary/harford-county/county-council/district-a/paula-r-mullis.md, content/primary/harford-county/county-council/district-c/patti-parker.md, content/primary/harford-county/county-council/district-c/susan-burdette.md, content/primary/harford-county/county-council/district-d/jerry-scarborough.md, content/primary/harford-county/county-council/district-e/diane-l-sengstacke.md, content/primary/harford-county/county-council/district-f/amy-altmann-jahnigen.md, content/primary/harford-county/county-council/district-f/john-michael-finlayson.md, content/state-house/district-1c/daniel-delmonte.md, content/state-house/district-2a/andrew-j-barnhart.md, content/state-house/district-2a/charlotte-mcbrearty.md, content/state-house/district-3a/jeremy-harbaugh.md, layouts/robots.txt
There were some false 404s caused by this
=> Fix capital letters in URLs

layouts/_default/baseof.html
This reverts commit e512c01b2b9161ec999cd045939d429139f42114.
=> Layout: Enable topper
